config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'help' => 'pages#help'

  get 'signup' => 'customers#new'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  resources :customers 

  resources :accounts do
    member do
      get :withdraw
    end
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :customer

  validates :acc_type, presence: true
  validates :acc_balance, presence: true

  before_save :generate_account_number

  private
  	def generate_account_number
  		#self.acc_num = PerfectRandom::rand.to_s if new_record?
  		self.acc_num = Time.now.to_i.to_s if new_record?
  	end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :accounts, dependent: :destroy

	before_save { self.email = email.downcase }
	
	validates :first_name, presence: true, length: {maximum: 50}
	validates :last_name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false}

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	#before_action :correct_customer, only: [:edit, :update]
	before_action :logged_in_user, only: [:create, :edit, :update]
	before_action :admin_user, only: [:index]

	def index
		@accounts = Account.paginate(page: params[:page])
	end

	def show
		@account = current_customer.accounts.build
		@transact = current_customer.accounts.build
		current_account = Account.find(params[:id])
		@account_balance = current_account.acc_balance
	end

	def new

	end

	def create
		@account = @current_customer.accounts.build(account_params)
		if @account.save
			flash[:success] = "Account successfully created!"
			redirect_to @current_customer
		else
			flash[:danger] = "Account creation failed!"
			redirect_to @customer
		end
	end

	def edit
		@title = "Transaction"
		@account = current_customer.accounts.find(params[:id])
		@account_balance = @account.acc_balance
	end

	def update
		@account = Account.find(params[:id])
		account_balance = @account.acc_balance
		@amount = params[:account][:amount].to_i
		if params[:commit] == "Withdraw"
			account_balance -= @amount
			if @account.update_attribute(:acc_balance, account_balance)
				flash.now[:success] = "Withdrawal of N#{@amount} successful"
      			render 'edit'
      		else
      			flash.now[:danger] = "Oops! Withdrawal failed!"
      			render 'edit'
      		end
      	else
      		account_balance += @amount
			if @account.update_attribute(:acc_balance, account_balance)
				flash.now[:success] = "Deposit of N#{@amount} successful"
	      		render 'edit'
	      	else
	      		flash.now[:danger] = "Oops! Withdrawal failed!"
	      		render 'edit'
	      	end
      	end
	end

	

	private

		def deposit
			
		end

		def account_params
			params.require(:account).permit(:acc_type, :acc_balance)
		end

		# ensure its the correct customer
		def correct_customer
			@account = current_customer.accounts.find_by(id: params[:id])
			redirect_to root_path if !(@account.customer_id == @current_customer.id)
		end

		def admin_user
	      redirect_to(root_url) unless current_customer.admin?
	    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private

	def logged_in_user
	  unless logged_in?
	    store_location
	    flash[:danger] = "Please log in."
	    redirect_to login_url
	   end
	end

	def admin_user
      redirect_to(root_url) unless current_customer.admin?
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_customer, only: [:show, :edit, :update]
  before_action :admin_user, only: :destroy

  def index
  	@customers = Customer.paginate(page: params[:page])
  end

  def show
    @title = "Customer Profile"
  	@customer = Customer.find_by(id: params[:id])
    session[:customer] = @customer.id
    @account = @customer.accounts.build
    #@accounts = @customer.accounts.where(Customer_id: session[:customer])
    @accounts = @customer.accounts.paginate(page: params[:page])
  end

  def new
  	@customer = Customer.new
  end

  def create
  	@customer = Customer.new(user_params)
  	if @customer.save
  		# Handle a successful save.
      log_in @customer
  		flash[:success] = "Welcome to the Sample App!"
  		redirect_to @customer
  	else
  		render 'new'
  	end
  end

  def edit
  	@customer = Customer.find(params[:id])
  end

  def update
  	@customer = Customer.find(params[:id])
    if @customer.update_attributes(user_params)
      # Handle a successful update
      flash[:success] = "Profile updated"
      redirect_to @customer
    else
      render 'edit'
    end
  end

  def destroy
  	Customer.find(params[:id]).destroy
    flash[:success] = "Customer deleted"
    redirect_to customers_url
  end

  private

  	def user_params
  		params.require(:customer).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  	end

    def correct_customer
      @customer = Customer.find(params[:id])
      redirect_to root_path unless current_customer?(@customer)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  end

  def help
  	@title = "Help"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@title = "Log in"
  end

  def create
  	customer = Customer.find_by(email: params[:session][:email].downcase)
    if customer && customer.authenticate(params[:session][:password])
    	# Log the user in and redirect to the user's show page.
      log_in customer
      redirect_to customer
    else
    	# Create an error message
    	flash.now[:danger] = 'Invalid email/password combination'
    	@title = "Log in"
  		render 'new'
  	end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	# Logs in the given user.
	def log_in(customer)
		session[:customer_id] = customer.id
	end

	def log_out
		session.delete(:customer_id)
		@current_customer = nil
	end

	# remembers in a persistent session
	def remember(customer)
		cookies.permanent.signed[:customer_id] = customer.id 
	end

	# returns the current user if any
	def current_customer
		if session[:customer_id]
			@current_customer ||= Customer.find_by(id: session[:customer_id])
		elsif cookies.signed[:customer_id]
			customer = Customer.find_by(id: cookies.signed[:customer_id])
			if customer
				log_in customer
				@current_customer = customer
			end
		end
	end

	def current_customer?(customer)
		customer == current_customer
	end

	#def customer
	#	@customer = Customer.find_by(id: session[:customer])
	#end

	def logged_in?
		!current_customer.nil?
	end

	# Stores the url to be accessed.
	def store_location
		session[:forwarding_url] = request.original_url if request.get?
	end
end

app/views/accounts/edit.html.erb
<h1>Account Transaction</h1>
<p class="center"><%= current_customer.first_name %> <%= current_customer.last_name %>
	| <span>Account Number<strong>: <%= @account.acc_num %></strong></span></p>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<ul class="nav nav-tabs ">
			<li class="active"><a href="#withdraw" data-toggle="tab">Withdrawal</a></li>
			<% #if current_customer.admin? %>
            	<li><a href="#deposit" data-toggle="tab">Deposit</a></li>
            <% #end %>
        </ul>
        <div class="tab-content">
			<div class="tab-pane active" id="withdraw">
				<%= form_for(@account) do |f| %>
					<%= f.label :amount %>
					<%= f.number_field :amount, value: 0, class: "form-control" %>
					<%= f.submit "Withdraw", class: "btn btn-primary" %>
				<% end %>
				Account balance N<%= @account.acc_balance %>
			</div>
			<% #if current_customer.admin? %>
				<div class="tab-pane" id="deposit">
					<%= form_for(@account) do |f| %>
						<%= f.label :amount %>
						<%= f.number_field :amount, value: 0, class: "form-control" %>
						<%= f.submit "Deposit", class: "btn btn-primary" %>
					<% end %>
					Account balance N<%= @account.acc_balance %>
				</div>
			<% #end %>
		</div>
		<p>Back to <%= link_to "My Accounts", customer_path(@current_customer) %></P>
	</div>
</div>

app/views/accounts/index.html.erb
<h1>All accounts</h1>
<div class="row">
	<div class="col-md-9 col-md-offset-3">
	    
	      <h3>Rails Bank Accounts</h3>
	      <ul class="accounts">
	      	<table class="table table-striped table-bordered">
	      		<thead>
		            <tr>
		              <th>Account Name</th>
		              <th>Account Email</th>
		              <th>Account Number</th>
		              <th>Type</th>
		              <th>Account Balance</th>
		             </tr>
		        </thead>
	        	<% @accounts.each do |account| %>
		            <tbody>
		            	<tr>
		            		<li>
		            			<td>
		        					<%= link_to account.customer.first_name, edit_account_path(account) %> <%=link_to account.customer.last_name%>
		        				</td>
		        				<td>
		        					<%= link_to account.customer.email, edit_account_path(account)%>
		        				</td>
						        <td>
						        	<%= link_to account.acc_num, edit_account_path(account) %>
						        </td>
						        <td>
						        	<%= link_to account.acc_type, edit_account_path(account) %>
						        </td>
						        <td>
						        	N<%= link_to account.acc_balance, edit_account_path(account) %>
						        </td>
		        			</li>
		        		</tr>	
	        		</tbody>
	        	<% end %>
	        </table>
	      </ul>
	      <% #will_paginate @accounts %>
	    
	</div>
</div>

app/views/customers/_customer.html.erb
<li>
	<%= customer.email %>
	<%= link_to customer.first_name, customer %>
	<%= link_to customer.last_name, customer %>
	<% if !current_customer?(customer) %>
    | <%= link_to "delete", customer, method: :delete,
                                  data: { confirm: "You sure?" } %>
  	<% end %>
</li>

app/views/customers/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

	<%= f.label :first_name %>
	<%= f.text_field :first_name, class: 'form-control' %>

	<%= f.label :last_name %>
	<%= f.text_field :last_name, class: 'form-control' %>

	<%= f.label :email %>
	<%= f.email_field :email, class: 'form-control' %>

	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>

	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>

	<%= f.submit :submit, class: "btn btn-primary" %>
<% end %>

app/views/customers/deposit.html.erb
<h1>Deposit</h1>
<div class="row">
	
</div>

app/views/customers/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'form' %>
	</div>
</div>

app/views/customers/index.html.erb
<h1>All customers</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @customers %>
</ul>

<%= will_paginate %>

app/views/customers/new.html.erb
<h1>Customers#new</h1>
<p>Find me in app/views/customers/new.html.erb</p>

<p>This will be a signup page for new customers.</p>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'form' %>
	</div>
</div>

app/views/customers/show.html.erb
<h1>Welcome <%= @customer.first_name %> <%= @customer.last_name %></h1>
<div class="center">
	<p>The following are your MyBank accounts</p>
</div>

<div class="row">
	<div class="col-md-3">
		<% #if current_customer.admin? %>	
			<p>Create new Account</p>

			<%= form_for(@account) do |f| %>
				<%= f.label :acc_type, class: "radiobutton inline" %>(you must select an account type. Savings/Current)
					<%= f.radio_button :acc_type, "savings", class: "" %><span>Savings</span>
					<%= f.radio_button :acc_type, "current", class: "" %><span>Current</span>
				<br>
				
				<%= f.label :Deposit %> (you can depisit any amount)
				<%= f.number_field :acc_balance, value: 0, class: "form-control" %>

				<%= f.submit "Create Account", class: "btn btn-primary" %>
			<% end %>
		<% #end %>
	</div>
	<div class="col-md-9">
	    <% if @customer.accounts.any? %>
	      <h3>Accounts (<%= @customer.accounts.count %>)</h3>
	      <ul class="accounts">
	      	<table class="table table-striped table-bordered">
	      		<thead>
		            <tr>
		              <th>Account Number</th>
		              <th>Type</th>
		              <th>Account Balance</th>
		             </tr>
		        </thead>
	        	<% @accounts.each do |account| %>
		            <tbody>
		            	<tr>
		            		<li>
		            			<td>
		        					<%= link_to account.acc_num, edit_account_path(account) %>
		        				</td>
		        				<td>
		        					<%= account.acc_type %>
		        				</td>
						        <td>
						        	N<%= account.acc_balance %>
						        </td>
		        			</li>
		        		</tr>	
	        		</tbody>
	        	<% end %>
	        </table>
	      </ul>
	      <% #will_paginate @accounts %>
	    <% end %>
	</div>
</div>

app/views/customers/withdraw.html.erb
<h1>Withdraw</h1>
<div class="row">
	<div>
		<%= form_for(current_customer) %>
		<% end %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="">MyBank</a>
    by <a href="">Innocent</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", "#" %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Rails Bank", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "My Accounts", customer_path(@current_customer) %></li>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBank | <%= @title %> <%= " " %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap/js/bootstrap.min', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'bootstrap/css/bootstrap.min', :media => 'all' %>
  <%= stylesheet_link_tag 'custom', :media => 'all' %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
	    <% flash.each do |message_type, message| %>
	      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
	    <% end %>

		<%= yield %>

		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on MyBank at the
  <a href="http://fast-mountain-75338.herokuapp.com/help">MyBank help page</a>.
  To get help on this MyBank app, see the
  <a href="http://fast-mountain-75338.herokuapp.com/help"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/pages/home.html.erb
<div class="center jumbotron">
	<h1>MyBank App</h1>

	<h2>
	  This is the home page for the
	  <a href="http://fast-mountain-75338.herokuapp.com">MyBank</a>
	  sample application.
	</h2>

	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("logo.png", alt: "MyBank logo"),					'http://fast-mountain-75338.herokuapp.com' %>